src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert; // Validation import
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity; //Validation for the doctrine component (Entity)

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 *@UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 10,
     *      max = 400,
     *      notInRangeMessage = "Vous devez entrer une surface minimale de {{ min }}m2 et maximale de {{ max }}m2",
     * )
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="text")
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold=false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

     /**
     * @ORM\Column(type="string")
     */
    private $imageFilename;


    function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice()
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }


    public function getImageFilename()
    {
        return $this->imageFilename;
    }

    public function setImageFilename($imageFilename)
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use App\Entity\Option;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms', null, [
                'label'=> 'Pièces'
            ])
            ->add('bedrooms', null, [
                'label'=> 'Chambres'
            ])
            ->add('floor', null, [
                'label'=> 'Etage'
            ])
            ->add('price', null, [
                'label'=> 'Prix'
            ])
            ->add('heat',/*null, [
                'label'=> 'Chauffage'
            ],*/ ChoiceType::class, [
                'choices'=>$this->getChoices()
            ])

            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true
            ])

            ->add('city', null, [
                'label'=> 'Ville'
            ])
            ->add('adress', null, [
                'label'=>'Adresse'
            ])
            ->add('postal_code', null, [
                'label'=> 'Code postal'
            ])
            ->add('sold', null, [
                'label'=>'Vendu'
            ])
            
            ->add('image', FileType::class, [
                'label' => 'Image (PNG file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Chargez une image au format PNG',
                    ])
                ],

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $key => $value) {
            $output[$value] = $key;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Property;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\SearchProperty;
use App\Form\SearchPropertyType;
use App\Entity\Contact;
use App\Form\ContactType;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use App\Notification\ContactNotification;
//use Symfony\Component\Form\Extension\Core\Type\SearchPropertyType;
//use Symfony\Component\HttpFoundation\File\UploadedFile;
//use Symfony\Component\HttpFoundation\File\Exception\FileException;




class PropertyController extends AbstractController
{

/**
 *@var PropertyRepository
 */

	public function __construct(PropertyRepository $repository)
	{
		$this->repository = $repository;
	}

/**
 *@route("/biens", name="property.index") 
 *@return Response
 */
	
	function index(PaginatorInterface $paginator, Request $request)
	{
		
			$search = new SearchProperty();
			$form = $this->createForm(SearchPropertyType::class, $search);
			$form->handleRequest($request);

			$properties = $paginator->paginate(
				$this->repository->findAllVisibleQuery($search),
				$request->query->getInt('page', 1),
				12
			);
		return $this->render('property/index.html.twig', [
			'current_menu' => 'properties',
			'properties' => $properties,
			'form' => $form->createView()
	]);
	}

/**
 *@route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"}) 
 *@param Property $property
 *@return Response
 */
	public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response
	{
		//Important for the referencement. if someone change the slug our id, it will redirect
		$contact = new Contact();
		$contact->setProperty($property);
		$form = $this->createForm(ContactType::class, $contact);

		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$notification->notify($contact);
			$this->addFlash('success', 'Votre message a bien été envoyé !');
			return $this->redirectToRoute('property.show', [
			'id' => $property->getId(),
			'slug' => $property->getSlug()
			]);
		}

		if ($property->getSlug() !== $slug) 
		{
			return $this->redirectToRoute('property.show', [
				'id' => $property->getId(),
				'slug' => $property->getSlug()
			], 301);
		}
		 return $this->render('property/show.html.twig', [
			'property' => $property,
			'current_menu' => 'properties',
			'form' => $form->createView()
	]);
	}
}

templates/property/_property.html.twig
<div class="card" style="width: 18rem; margin: auto;">
  <div class="card-body">
    <h5 class="card-title">
    	<a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">{{ property.title }}</a>
    </h5>
     <p class="card-text">
     	{{ property.surface }} m2 {{ property.city }} ({{ property.postalCode }})
     </p>
     <div class="text-primary" style="font-size: 2rem; font-weight: bold;">
     	{{ property.formatedPrice }} €
     </div>
  </div>
</div>

templates/property/index.html.twig
{% extends('base.html.twig') %}

{% block title %}  Our Properties !  {% endblock %}

{% block body %}
    <div class="jombotron mt-4" style="width:50%; margin:auto;">
        <div class=container>
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">               
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col"> 
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col"> 
                    {{ form_row(form.option) }}
                </div>
                <div class="col"> 
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

	<div class="container text-center mt-4">
		<h1>See all of our Properties !</h1>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    	</p>
        <div class=row>
            {% for property in properties %}
                <div class="col-md 4">
                     {% include('property/_property.html.twig')%}
                </div>
            {% endfor %}
        </div>
        <diva class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
	</div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig'%}

{% block title property.title %}

{% block body %}
	<div class="jombotron">
		<div class="container">
			<div class="row">
			<div class="col-md-8">

			</div>
			<div class="col-md-8">
				<h1>{{ property.title }}</h1>
				<h2>{{ property.rooms}} pièces - {{property.surface}}m2</h2>
				<div class="text-primary" style="font-size:4rem">{{ property.formatedPrice}}€</div>
				<a href="#" class="btn btn-primary">Contactez l'agence</a>
				
				<div id="contactForm" class="mt-4">
					{{ form_start(form) }}
						<div class="row">
							<div class="col"> {{ form_row(form.firstname) }}
							<div class="col"> {{ form_row(form.lastname) }}
						</div>
						<div class="row">
							<div class="col"> {{ form_row(form.phone) }}
							<div class="col"> {{ form_row(form.email) }}
						</div>
					{{ form_rest(form) }}
						<div class="form-group">
							<button class="btn btn-primary"> Envoyer </button>
						</div>
					{{ form_end(form) }}
				</div>
				
			</div>
		</div>

		</div>
	</div>

	<div class="container mt-4">
		
		<p>
			{{ property.description | nl2br }}
		</p>
		<div class="row">
			<div class="col-md-8">
				<h2>Caractéristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ property.surface }} m2</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ property.rooms }} </td>
					</tr>
					<tr>
						<td>Chambre</td>
						<td>{{ property.bedrooms }} </td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{ property.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{ property.heatType }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Spécificités</h2>		
			</div>
		</div>
	</div>

{% endblock %}